# Matriks

## Definisi Matriks

Matriks adalah angka-angka yang disusun sedemikian sehingga menyerupai persegipanjang berdasarkan urutan baris dan kolom. Angka-angka yang menyusun matriks disebut sebagai unsur atau elemen. Umumnya, matriks berada di dalam tanda kurung dan dinyatakan sebagai huruf kapital. Sementara itu, unsur atau elemen dinyatakan sebagai huruf kecil serta memiliki indeks. Indeks tersebut menyatakan letak baris dan kolom unsur. Baris adalah susunan angka yang arahnya horizontal atau mendatar.

### Ordo Matriks
Ordo matriks adalah ukuran dari matriks yang dinyatakan dalam bentuk m × n, di mana:

- m adalah jumlah baris.

- n adalah jumlah kolom.

Misalnya, jika sebuah matriks memiliki 3 baris dan 2 kolom, maka ordonya adalah 3 × 2.

### Contoh Matriks Dengan Berbagai Ordo :

1. Matriks Ordo 4 × 4

$$
B = \begin{bmatrix}
1 & 2 & 3 & 4 \\
5 & 6 & 7 & 8 \\
9 & 10 & 11 & 12 \\
13 & 14 & 15 & 16
\end{bmatrix}
$$

2. Matriks Ordo 3 × 3

$$
C = \begin{bmatrix}
2 & 4 & 6 \\
8 & 10 & 12 \\
14 & 16 & 18
\end{bmatrix}
$$

3. Matriks Ordo 3 × 2

$$
D = \begin{bmatrix}
1 & 2 \\
3 & 4 \\
5 & 6
\end{bmatrix}
$$

4. Matriks Ordo 2 × 4

$$
E = \begin{bmatrix}
7 & 8 & 9 & 10 \\
11 & 12 & 13 & 14
\end{bmatrix}
$$

5. Matriks Ordo 1 × 3 (Matriks Baris)

$$
F = \begin{bmatrix} 3 & 5 & 7 \end{bmatrix}
$$

6. Matriks Ordo 3 × 1 (Matriks Kolom)

$$
G = \begin{bmatrix}
8 \\
6 \\
4
\end{bmatrix}
$$


## Operasi Aritmatika Matriks

Operasi aritmatika adalah sekumpulan empat operasi dasar yang dilakukan untuk menambah, mengurangi, mengalikan, atau membagi dua atau lebih kuantitas. Operasi ini meliputi studi angka termasuk urutan operasi yang berguna dalam semua bagian matematika lainnya seperti aljabar , penanganan data , dan geometri .

## Penjumlahan Matriks

Penjumlahan matriks adalah operasi penjumlahan dua matriks dengan menjumlahkan komponen-komponennya yang seletak. Dua matriks dapat dijumlahkan jika jumlah baris dan kolomnya sama. Matriks hasil penjumlahannya juga akan memiliki ordo yang sama.

### Konsep Penjumlahan Matrik

Berikut contoh penjumlahan matriks :

In [ ]:
import numpy as np

# 1. Definisikan matriks A dan B dengan angka baru
A = np.array([[3, 6, 9],
              [2, 5, 8],
              [4, 7, 10]])

B = np.array([[1, 4, 7],
              [3, 6, 9],
              [2, 5, 8]])

# 2. Hitung penjumlahan matriks
penjumlahan = A + B

# 3. Cetak output sesuai format yang diminta
print(A)
print()
print(B)
print("\nHasil Penjumlahan:")
print(penjumlahan)


[[ 3  6  9]
 [ 2  5  8]
 [ 4  7 10]]

[[1 4 7]
 [3 6 9]
 [2 5 8]]

Hasil Penjumlahan:
[[ 4 10 16]
 [ 5 11 17]
 [ 6 12 18]]


## Perkalian Matriks

Perkalian matriks adalah operasi yang melibatkan dua matriks untuk menghasilkan matriks baru. Namun, tidak semua matriks dapat dikalikan. Untuk melakukan perkalian matriks, ada beberapa aturan yang harus diikuti.

Sebuah matriks A berukuran m × n bisa dikalikan dengan matriks B berukuran n × p jika jumlah kolom matriks pertama (n) sama dengan jumlah baris matriks kedua (n).
Hasil perkalian akan menjadi matriks baru berukuran m × p.

### Konsep Perkalian Matriks

Berikut contoh perkalian matriks :

In [ ]:
import numpy as np

# 1. Definisikan matriks A dan B dengan angka baru
A = np.array([[2, 3, 4],
              [5, 6, 7],
              [8, 9, 10]])

B = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

# 2. Hitung perkalian matriks
perkalian = np.matmul(A, B)

# 3. Cetak matriks A dan B
print("Matriks A:")
print(A)
print("\nMatriks B:")
print(B)

# 4. Tampilkan langkah-langkah perhitungan setiap elemen matriks hasil
print("\nLangkah-Langkah Perkalian Matriks:")

# Loop untuk menampilkan perhitungan tiap elemen
for i in range(len(A)):
    for j in range(len(B[0])):
        langkah = " + ".join([f"{A[i][k]}×{B[k][j]}" for k in range(len(A[0]))])
        hasil = perkalian[i][j]
        print(f"Elemen ({i+1},{j+1}): {langkah} = {hasil}")

# 5. Cetak hasil akhir perkalian matriks
print("\nHasil Perkalian Matriks:")
print(perkalian)


Matriks A:
[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]

Matriks B:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Langkah-Langkah Perkalian Matriks:
Elemen (1,1): 2×1 + 3×4 + 4×7 = 42
Elemen (1,2): 2×2 + 3×5 + 4×8 = 51
Elemen (1,3): 2×3 + 3×6 + 4×9 = 60
Elemen (2,1): 5×1 + 6×4 + 7×7 = 78
Elemen (2,2): 5×2 + 6×5 + 7×8 = 96
Elemen (2,3): 5×3 + 6×6 + 7×9 = 114
Elemen (3,1): 8×1 + 9×4 + 10×7 = 114
Elemen (3,2): 8×2 + 9×5 + 10×8 = 141
Elemen (3,3): 8×3 + 9×6 + 10×9 = 168

Hasil Perkalian Matriks:
[[ 42  51  60]
 [ 78  96 114]
 [114 141 168]]


## Penyelesaian persamaan menggunakan invers matrik

Kita diberikan sistem persamaan linear:


$
\begin{aligned}
    -7x_1 - 6x_2 - 12x_3 &= -33 \\
    5x_1 + 5x_2 + 7x_3 &= 24 \\
    x_1 + 4x_3 &= 5
\end{aligned}
$


#### **1. Bentuk Matriks**

Sistem persamaan di atas dapat dituliskan dalam bentuk matriks:


$
A \mathbf{x} = \mathbf{b}
$


dengan:


$
A =
\begin{bmatrix}
-7 & -6 & -12 \\
5 & 5 & 7 \\
1 & 0 & 4
\end{bmatrix},
\quad
\mathbf{x} =
\begin{bmatrix}
x_1 \\ x_2 \\ x_3
\end{bmatrix},
\quad
\mathbf{b} =
\begin{bmatrix}
-33 \\ 24 \\ 5
\end{bmatrix}
$


Penyelesaian sistem menggunakan invers matriks diberikan oleh:

$
\mathbf{x} = A^{-1} \mathbf{b}
$

Kita akan mencari $ A^{-1} $ menggunakan operasi baris elementer.

---

#### **2. Menentukan $ A^{-1} $ Menggunakan Operasi Baris Elementer**

Kita mulai dengan matriks augmented:


$
\left[ A \,|\, I \right] =
\left[
\begin{array}{ccc|ccc}
-7 & -6 & -12 & 1 & 0 & 0 \\
5 & 5 & 7 & 0 & 1 & 0 \\
1 & 0 & 4 & 0 & 0 & 1
\end{array}
\right]
$


**Langkah 1: Ubah elemen (1,1) menjadi 1**

Kita bagi baris pertama dengan $ -7 $:


$
\left[
\begin{array}{ccc|ccc}
1 & \frac{6}{7} & \frac{12}{7} & -\frac{1}{7} & 0 & 0 \\
5 & 5 & 7 & 0 & 1 & 0 \\
1 & 0 & 4 & 0 & 0 & 1
\end{array}
\right]
$


**Langkah 2: Nulifikasi elemen (2,1) dan (3,1)**

Baris kedua: $ R_2 \leftarrow R_2 - 5R_1 $  

Baris ketiga: $ R_3 \leftarrow R_3 - R_1 $

$
\left[
\begin{array}{ccc|ccc}
1 & \frac{6}{7} & \frac{12}{7} & -\frac{1}{7} & 0 & 0 \\
0 & \frac{5}{7} & \frac{1}{7} & \frac{5}{7} & 1 & 0 \\
0 & -\frac{6}{7} & \frac{16}{7} & \frac{1}{7} & 0 & 1
\end{array}
\right]
$

**Langkah 3: Ubah elemen (2,2) menjadi 1**  

Kita kalikan baris kedua dengan $ \frac{7}{5} $:

$
\left[
\begin{array}{ccc|ccc}
1 & \frac{6}{7} & \frac{12}{7} & -\frac{1}{7} & 0 & 0 \\
0 & 1 & \frac{1}{5} & \frac{1}{5} & \frac{7}{5} & 0 \\
0 & -\frac{6}{7} & \frac{16}{7} & \frac{1}{7} & 0 & 1
\end{array}
\right]
$

**Langkah 4: Nulifikasi elemen (1,2) dan (3,2)**

Baris pertama: $ R_1 \leftarrow R_1 - \frac{6}{7} R_2 $  

Baris ketiga: $ R_3 \leftarrow R_3 + \frac{6}{7} R_2 $

$
\left[
\begin{array}{ccc|ccc}
1 & 0 & \frac{10}{7} & -\frac{5}{21} & -\frac{6}{5} & 0 \\
0 & 1 & \frac{1}{5} & \frac{1}{5} & \frac{7}{5} & 0 \\
0 & 0 & \frac{22}{7} & \frac{11}{35} & \frac{42}{35} & 1
\end{array}
\right]
$

**Langkah 5: Ubah elemen (3,3) menjadi 1**  

Kita kalikan baris ketiga dengan $ \frac{7}{22} $:

$
\left[
\begin{array}{ccc|ccc}
1 & 0 & \frac{10}{7} & -\frac{5}{21} & -\frac{6}{5} & 0 \\
0 & 1 & \frac{1}{5} & \frac{1}{5} & \frac{7}{5} & 0 \\
0 & 0 & 1 & \frac{1}{10} & \frac{21}{22} & \frac{7}{22}
\end{array}
\right]
$

**Langkah 6: Nulifikasi elemen (1,3) dan (2,3)**

Baris pertama: $ R_1 \leftarrow R_1 - \frac{10}{7} R_3 $  

Baris kedua: $ R_2 \leftarrow R_2 - \frac{1}{5} R_3 $

$
\left[
\begin{array}{ccc|ccc}
1 & 0 & 0 & -\frac{8}{21} & -\frac{9}{5} & -\frac{10}{22} \\
0 & 1 & 0 & \frac{1}{5} - \frac{1}{50} & \frac{7}{5} - \frac{21}{110} & -\frac{7}{110} \\
0 & 0 & 1 & \frac{1}{10} & \frac{21}{22} & \frac{7}{22}
\end{array}
\right]
$

Setelah disederhanakan, kita dapatkan invers matriks $ A^{-1} $:

$
A^{-1} =
\begin{bmatrix}
-\frac{8}{21} & -\frac{9}{5} & -\frac{5}{11} \\
\frac{2}{7} & \frac{37}{35} & -\frac{7}{55} \\
\frac{1}{10} & \frac{21}{22} & \frac{7}{22}
\end{bmatrix}
$

---

#### **3. Menghitung $ \mathbf{x} = A^{-1} \mathbf{b} $**

$
\mathbf{x} =
\begin{bmatrix}
-\frac{8}{21} & -\frac{9}{5} & -\frac{5}{11} \\
\frac{2}{7} & \frac{37}{35} & -\frac{7}{55} \\
\frac{1}{10} & \frac{21}{22} & \frac{7}{22}
\end{bmatrix}
\begin{bmatrix}
-33 \\ 24 \\ 5
\end{bmatrix}
$

Setelah dihitung, diperoleh:

$
\mathbf{x} =
\begin{bmatrix}
1 \\ 2 \\ 1
\end{bmatrix}
$

Jadi, solusi dari sistem persamaan adalah:

$
x_1 = 1, \quad x_2 = 2, \quad x_3 = 1
$