# SVD (Singular Value Decomposition)

## Apa itu SVD?

**SVD (Singular Value Decomposition)** adalah salah satu teknik paling penting dalam aljabar linear yang digunakan untuk **memecah sebuah matriks menjadi tiga komponen utama**, sehingga mempermudah berbagai operasi matematis, khususnya pada data berukuran besar.

Jika kamu punya sebuah matriks $A$, maka SVD menuliskan matriks itu sebagai:

$$
A = U \Sigma V^T
$$

Dengan penjelasan sebagai berikut:

* $A$ adalah matriks asli berukuran $m \times n$
* $U$ adalah matriks ortogonal berukuran $m \times m$ (kolomnya disebut *left singular vectors*)
* $\Sigma$ (sigma) adalah **matriks diagonal** berukuran $m \times n$, berisi nilai-nilai singular (singular values)
* $V^T$ adalah transpos dari matriks ortogonal $V$ berukuran $n \times n$ (kolomnya disebut *right singular vectors*)

---

## Kegunaan SVD

1. Reduksi Dimensi

Singular Value Decomposition (SVD) berperan dalam menyederhanakan data dengan mengurangi jumlah variabel atau fitur, suatu proses yang dikenal sebagai reduksi dimensi. Dengan memilih hanya sebagian kecil dari nilai dan vektor singular yang paling relevan, SVD mampu menciptakan representasi data yang lebih ringkas tanpa kehilangan informasi utama. Salah satu contoh penerapannya adalah dalam metode Principal Component Analysis (PCA).

2. Kompresi Data

SVD juga berfungsi untuk melakukan kompresi data, misalnya pada gambar dan audio, dengan menghapus bagian data yang kurang penting dan tetap menjaga informasi utama. Dalam konteks gambar, SVD dapat memperkecil ukuran file tanpa mengorbankan kualitas visual secara signifikan.

3. Pemrosesan Sinyal

Dalam bidang pengolahan sinyal, SVD digunakan untuk menyaring sinyal serta mengurangi noise atau gangguan. Teknik ini membantu dalam menemukan pola-pola penting di dalam sinyal dan memisahkannya dari elemen yang tidak diinginkan.

4. Analisis Citra

SVD berguna dalam mengekstraksi ciri-ciri penting dari gambar, sehingga sering diterapkan dalam pengenalan wajah maupun pola visual. Selain itu, metode ini juga digunakan dalam proses pemulihan gambar yang mengalami kerusakan atau penurunan kualitas.

5. Sistem Rekomendasi

Dalam sistem rekomendasi, SVD dimanfaatkan untuk memperkirakan preferensi pengguna terhadap suatu item dengan mendekomposisi matriks user-item. Pendekatan ini memungkinkan sistem menemukan pola tersembunyi dan memberikan saran yang lebih tepat dan relevan.

6. Penyelesaian Masalah Kuadrat Terkecil

SVD digunakan untuk menyelesaikan masalah regresi dan pencocokan data, khususnya dalam pendekatan kuadrat terkecil. Secara umum, SVD merupakan alat yang sangat berguna untuk mengungkap struktur tersembunyi dalam data dan menyoroti informasi utama, sehingga banyak digunakan dalam bidang statistik, teknik, maupun sains data.

---


##  Bagaimana Formula SVD

Secara matematis, diberikan matriks $A \in \mathbb{R}^{m \times n}$, maka:

$$
A = U \Sigma V^T
$$

Langkah-langkah perhitungan:

1. **Hitung $A^TA$** dan **$AA^T$**
2. **Eigen decomposition** dilakukan terhadap dua matriks tersebut:

   * Eigen vektor dari $AA^T$ digunakan untuk membentuk $U$
   * Eigen vektor dari $A^TA$ digunakan untuk membentuk $V$
3. **Singular values** adalah akar kuadrat dari eigenvalue $A^TA$ atau $AA^T$, yang diletakkan pada diagonal matriks $\Sigma$

Contoh bentuk $\Sigma$ untuk matriks 3x3:

$$
\Sigma =
\begin{bmatrix}
\sigma_1 & 0 & 0 \\
0 & \sigma_2 & 0 \\
0 & 0 & \sigma_3 \\
\end{bmatrix}
$$

Dengan $\sigma_1 \geq \sigma_2 \geq \sigma_3 \geq 0$




## **Soal:**

Misal matriks A:

$$
A = \begin{bmatrix}
3 & 1 \\
1 & 3 \\
\end{bmatrix}
$$

---

##  **Langkah 1: Hitung $A^T A$ dan $A A^T$**

Karena $A$ adalah matriks simetris $2 \times 2$, maka $A^T = A$.

$$
A^T A = A A =
\begin{bmatrix}
3 & 1 \\
1 & 3 \\
\end{bmatrix}
\begin{bmatrix}
3 & 1 \\
1 & 3 \\
\end{bmatrix}
=
\begin{bmatrix}
3×3 + 1×1 & 3×1 + 1×3 \\
1×3 + 3×1 & 1×1 + 3×3 \\
\end{bmatrix}
=
\begin{bmatrix}
9 + 1 & 3 + 3 \\
3 + 3 & 1 + 9 \\
\end{bmatrix}
=
\begin{bmatrix}
10 & 6 \\
6 & 10 \\
\end{bmatrix}
$$

---

##  **Langkah 2: Cari Eigenvalue dari $A^T A$**

Misal $\lambda$ adalah eigenvalue, maka:

$$
\det(A^TA - \lambda I) = 0
$$

$$
\begin{vmatrix}
10 - \lambda & 6 \\
6 & 10 - \lambda \\
\end{vmatrix} = 0
$$

$$
(10 - \lambda)^2 - 36 = 0
\Rightarrow (10 - \lambda)^2 = 36
\Rightarrow 10 - \lambda = \pm 6
$$

$$
\lambda_1 = 4,\quad \lambda_2 = 16
$$

---

##  **Langkah 3: Hitung Singular Values**

$$
\sigma_i = \sqrt{\lambda_i}
\Rightarrow
\sigma_1 = \sqrt{16} = 4,\quad \sigma_2 = \sqrt{4} = 2
$$

---

## **Langkah 4: Cari V (eigenvector dari $A^TA$)**

Gunakan $A^TA = \begin{bmatrix} 10 & 6 \\ 6 & 10 \end{bmatrix}$

### Untuk $\lambda = 16$:

$$
(A^TA - 16I) v = 0
\Rightarrow
\begin{bmatrix}
-6 & 6 \\
6 & -6 \\
\end{bmatrix}
\Rightarrow
v_1 = \begin{bmatrix}
1 \\
1 \\
\end{bmatrix} \quad \text{(sebelum normalisasi)}
$$

Normalisasi:

$$
v_1 = \frac{1}{\sqrt{2}} \begin{bmatrix} 1 \\ 1 \end{bmatrix}
$$

### Untuk $\lambda = 4$:

$$
(A^TA - 4I) v = 0
\Rightarrow
\begin{bmatrix}
6 & 6 \\
6 & 6 \\
\end{bmatrix}
\Rightarrow
v_2 = \begin{bmatrix}
1 \\
-1 \\
\end{bmatrix}
\Rightarrow
v_2 = \frac{1}{\sqrt{2}} \begin{bmatrix} 1 \\ -1 \end{bmatrix}
$$

---

##  **Langkah 5: Bentuk $\Sigma$ dan $V$**

$$
\Sigma = \begin{bmatrix}
4 & 0 \\
0 & 2 \\
\end{bmatrix}, \quad
V = \left[
\frac{1}{\sqrt{2}} \begin{bmatrix} 1 \\ 1 \end{bmatrix},
\frac{1}{\sqrt{2}} \begin{bmatrix} 1 \\ -1 \end{bmatrix}
\right]
=
\frac{1}{\sqrt{2}}
\begin{bmatrix}
1 & 1 \\
1 & -1 \\
\end{bmatrix}
$$

---

##  **Langkah 6: Hitung $U$** dengan rumus:

$$
U_i = \frac{1}{\sigma_i} A v_i
$$

### Untuk $\sigma_1 = 4$, $v_1 = \frac{1}{\sqrt{2}} \begin{bmatrix} 1 \\ 1 \end{bmatrix}$

$$
u_1 = \frac{1}{4} A v_1 = \frac{1}{4} A \cdot \frac{1}{\sqrt{2}} \begin{bmatrix} 1 \\ 1 \end{bmatrix}
= \frac{1}{4\sqrt{2}} \begin{bmatrix} 3+1 \\ 1+3 \end{bmatrix}
= \frac{1}{4\sqrt{2}} \begin{bmatrix} 4 \\ 4 \end{bmatrix}
= \frac{1}{\sqrt{2}} \begin{bmatrix} 1 \\ 1 \end{bmatrix}
$$

### Untuk $\sigma_2 = 2$, $v_2 = \frac{1}{\sqrt{2}} \begin{bmatrix} 1 \\ -1 \end{bmatrix}$

$$
u_2 = \frac{1}{2} A v_2 = \frac{1}{2\sqrt{2}} \begin{bmatrix} 3 - 1 \\ 1 - 3 \end{bmatrix}
= \frac{1}{2\sqrt{2}} \begin{bmatrix} 2 \\ -2 \end{bmatrix}
= \frac{1}{\sqrt{2}} \begin{bmatrix} 1 \\ -1 \end{bmatrix}
$$

---

## Hasil Akhir SVD

$$
U = \frac{1}{\sqrt{2}} \begin{bmatrix}
1 & 1 \\
1 & -1 \\
\end{bmatrix},\quad
\Sigma = \begin{bmatrix}
4 & 0 \\
0 & 2 \\
\end{bmatrix},\quad
V^T = \left(\frac{1}{\sqrt{2}} \begin{bmatrix}
1 & 1 \\
1 & -1 \\
\end{bmatrix}\right)^T
$$

---


In [1]:
import numpy as np

# Matriks asli
A = np.array([
    [3, 1],
    [1, 3]
])

# SVD dengan NumPy
U, S, VT = np.linalg.svd(A)

print("Matrix A:")
print(A)
print("\nU:")
print(U)
print("\nSingular values (S):")
print(S)
print("\nV^T:")
print(VT)

# Bentuk S ke dalam bentuk matriks diagonal (Sigma)
Sigma = np.zeros_like(A, dtype=float)
np.fill_diagonal(Sigma, S)

print("\nSigma:")
print(Sigma)

# Perkalian kembali: U @ Sigma @ V^T
A_reconstructed = U @ Sigma @ VT

print("\nRekonstruksi A dari UΣV^T:")
print(A_reconstructed)

# Cek apakah hasilnya sama
print("\nApakah A sama dengan rekonstruksi? ", np.allclose(A, A_reconstructed))


Matrix A:
[[3 1]
 [1 3]]

U:
[[-0.70710678 -0.70710678]
 [-0.70710678  0.70710678]]

Singular values (S):
[4. 2.]

V^T:
[[-0.70710678 -0.70710678]
 [-0.70710678  0.70710678]]

Sigma:
[[4. 0.]
 [0. 2.]]

Rekonstruksi A dari UΣV^T:
[[3. 1.]
 [1. 3.]]

Apakah A sama dengan rekonstruksi?  True


## Perhitungan Manual Matriks 4x2
Diketahui:
$$
A =
\begin{bmatrix}
3 & 7 \\
2 & 5 \\
4 & 3 \\
1 & 1 \\
\end{bmatrix}
\quad \text{(ukuran 4 × 2)}
$$

Kita akan melakukan **Singular Value Decomposition (SVD)** terhadap matriks ini, yaitu:

$$
A = U \cdot \Sigma \cdot V^T
$$


Langkah-Langkah Singkat (Manual Konsep)

1. Hitung $A^T A$

Karena A adalah 4×2, maka $A^T$ adalah 2×4, sehingga:

$$
A^T A =
\begin{bmatrix}
3 & 2 & 4 & 1 \\
7 & 5 & 3 & 1 \\
\end{bmatrix}
\cdot
\begin{bmatrix}
3 & 7 \\
2 & 5 \\
4 & 3 \\
1 & 1 \\
\end{bmatrix}
$$

Kalikan baris × kolom:

$$
A^T A =
\begin{bmatrix}
3^2 + 2^2 + 4^2 + 1^2 & 3×7 + 2×5 + 4×3 + 1×1 \\
3×7 + 2×5 + 4×3 + 1×1 & 7^2 + 5^2 + 3^2 + 1^2 \\
\end{bmatrix}
$$

Hitung elemen-elemennya:

* $3^2 + 2^2 + 4^2 + 1^2 = 9 + 4 + 16 + 1 = 30$
* $3×7 + 2×5 + 4×3 + 1×1 = 21 + 10 + 12 + 1 = 44$
* $7^2 + 5^2 + 3^2 + 1^2 = 49 + 25 + 9 + 1 = 84$

Jadi:

$$
A^T A =
\begin{bmatrix}
30 & 44 \\
44 & 84 \\
\end{bmatrix}
$$


2. Hitung **eigenvalue** dari $A^T A$

Cari $\lambda$ dari:

$$
\left|
\begin{matrix}
30 - \lambda & 44 \\
44 & 84 - \lambda \\
\end{matrix}
\right| = 0
$$

$$
(30 - \lambda)(84 - \lambda) - 44^2 = 0
\Rightarrow
\lambda^2 - 114\lambda + (2520 - 1936) = 0
\Rightarrow
\lambda^2 - 114\lambda + 584 = 0
$$

Gunakan rumus kuadrat:

$$
\lambda = \frac{114 \pm \sqrt{114^2 - 4 \cdot 584}}{2}
= \frac{114 \pm \sqrt{12996 - 2336}}{2}
= \frac{114 \pm \sqrt{10660}}{2}
$$

$$
\sqrt{10660} \approx 103.25
$$

$$
\lambda_1 \approx \frac{114 + 103.25}{2} = 108.625, \quad
\lambda_2 \approx \frac{114 - 103.25}{2} = 5.375
$$


3. Cari **singular values** = akar dari eigenvalue:

$$
\sigma_1 = \sqrt{108.625} \approx 10.42, \quad
\sigma_2 = \sqrt{5.375} \approx 2.32
$$


4. Bangun matriks $\Sigma$

Karena A adalah 4×2, maka $\Sigma$ adalah 4×2:

$$
\Sigma =
\begin{bmatrix}
10.42 & 0 \\
0 & 2.32 \\
0 & 0 \\
0 & 0 \\
\end{bmatrix}
$$


5. Matriks $V$ dan $U$

* $V$ berasal dari eigenvector $A^T A$
* $U = \frac{1}{\sigma_i} A v_i$


Kesimpulan SVD:

$$
A_{4×2} = U_{4×4} \cdot \Sigma_{4×2} \cdot V^T_{2×2}
$$

Dengan:

* $\Sigma = \begin{bmatrix} 10.42 & 0 \\ 0 & 2.32 \\ 0 & 0 \\ 0 & 0 \end{bmatrix}$
* $V$: eigenvector dari $A^T A$
$$
V^T =
\begin{bmatrix}
-0.488 & -0.873 \\
-0.873 &  0.488 \\
\end{bmatrix}
$$

> Baris-barisnya adalah vektor eigen dari $A^T A$

* $U$: dihitung dari $Av_i / \sigma_i$

$$
U =
\begin{bmatrix}
-0.727 & -0.345 & -0.574 & -0.153 \\
-0.512 & -0.300 &  0.792 &  0.139 \\
-0.439 &  0.874 &  0.082 & -0.195 \\
-0.131 &  0.166 & -0.190 &  0.959 \\
\end{bmatrix}
$$

> Kolom-kolom $U$ adalah vektor ortonormal yang membentang ruang kolom dari $A$.

In [2]:
import numpy as np

# Matriks asli
A = np.array([
    [3, 7],
    [2, 5],
    [4, 3],
    [1, 1]
])

# SVD dengan NumPy
U, S, VT = np.linalg.svd(A)

print("Matrix A:")
print(A)
print("\nU:")
print(U)
print("\nSingular values (S):")
print(S)
print("\nV^T:")
print(VT)

# Bentuk S ke dalam bentuk matriks diagonal (Sigma)
Sigma = np.zeros_like(A, dtype=float)
np.fill_diagonal(Sigma, S)

print("\nSigma:")
print(Sigma)

# Perkalian kembali: U @ Sigma @ V^T
A_reconstructed = U @ Sigma @ VT

print("\nRekonstruksi A dari UΣV^T:")
print(A_reconstructed)

# Cek apakah hasilnya sama
print("\nApakah A sama dengan rekonstruksi? ", np.allclose(A, A_reconstructed))


Matrix A:
[[3 7]
 [2 5]
 [4 3]
 [1 1]]

U:
[[-0.72667296 -0.34526321 -0.57386797 -0.15302052]
 [-0.51235825 -0.300381    0.79239419  0.13918232]
 [-0.4386146   0.87355405  0.0817107  -0.19453511]
 [-0.13058586  0.16573437 -0.19002726  0.95883737]]

Singular values (S):
[10.42226645  2.31869834]

V^T:
[[-0.48835631 -0.87264432]
 [ 0.87264432 -0.48835631]]

Sigma:
[[10.42226645  0.        ]
 [ 0.          2.31869834]
 [ 0.          0.        ]
 [ 0.          0.        ]]

Rekonstruksi A dari UΣV^T:
[[3. 7.]
 [2. 5.]
 [4. 3.]
 [1. 1.]]

Apakah A sama dengan rekonstruksi?  True
